<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>Vitor Martineli Gonçalves</Authors>
    <Description>Helper to work with notifications.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>

</Project>
